# Generated by Django 4.2.7 on 2026-07-29 10:31

import clinic_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=clinic_backend.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
