# Generated by Django 4.2.7 on 2026-03-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("DOCTOR", "Doctor"),
                    ("STAFF", "Staff"),
                    ("PATIENT", "Patient"),
                    ("LAB_TECHNICIAN", "Lab Technician"),
                ],
                default="PATIENT",
                max_length=15,
            ),
        ),
    ]
