# Generated by Django 4.2.7 on 2026-02-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_add_prescriptions_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='balance',
        ),
    ]
