# Generated by Django 4.2.7 on 2026-02-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billing_bed_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='bed_charge_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billing',
            name='bed_days',
            field=models.IntegerField(default=0),
        ),
    ]
