# Generated by Django 4.2.7 on 2026-03-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_billing_bed_charge_per_day_billing_bed_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="lab_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
