# Generated by Django 4.2.7 on 2026-02-04 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('bed_type', models.CharField(choices=[('STANDARD', 'Standard Bed'), ('ADJUSTABLE', 'Adjustable Bed'), ('ICU', 'ICU Bed'), ('VENTILATOR', 'Bed with Ventilator'), ('PEDIATRIC', 'Pediatric Bed')], default='STANDARD', max_length=20)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance'), ('CLEANING', 'Needs Cleaning')], default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ward_type', models.CharField(choices=[('GENERAL', 'General Ward'), ('ICU', 'Intensive Care Unit'), ('PRIVATE', 'Private Room'), ('SEMI_PRIVATE', 'Semi-Private Room'), ('EMERGENCY', 'Emergency Ward'), ('MATERNITY', 'Maternity Ward'), ('PEDIATRIC', 'Pediatric Ward')], max_length=20)),
                ('floor_number', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCHARGED', 'Discharged')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='beds.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_allocations', to='patients.patient')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='beds.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ward', 'bed_number')},
        ),
    ]
