# Generated by Django 4.2.7 on 2026-07-29 10:31

import clinic_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedallocation',
            name='notes',
            field=clinic_backend.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bedallocation',
            name='reason',
            field=clinic_backend.fields.EncryptedTextField(blank=True),
        ),
    ]
