# Generated by Django 4.2.7 on 2026-02-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_bedrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedallocation',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
    ]
