# Generated by Django 4.2.7 on 2026-02-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='case_type',
            field=models.CharField(choices=[('NEW', 'New'), ('OLD', 'Old')], default='NEW', max_length=3),
        ),
    ]
