# Generated by Django 4.2.7 on 2026-07-29 10:31

import clinic_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='admin_reply',
            field=clinic_backend.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='message',
            field=clinic_backend.fields.EncryptedTextField(),
        ),
    ]
