# Generated by Django 4.2.7 on 2026-07-29 10:31

import clinic_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=clinic_backend.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=clinic_backend.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=clinic_backend.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=clinic_backend.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
