# Generated by Django 4.2.7 on 2026-02-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_uhid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
