# Generated by Django 4.2.7 on 2026-02-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_profile_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='profile_completed',
        ),
    ]
