# Generated by Django 4.2.7 on 2026-03-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_remove_patient_profile_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
    ]
