# Generated by Django 4.2.7 on 2026-03-26 05:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='report_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='lab_report'),
        ),
    ]
