# Generated by Django 4.2.7 on 2026-02-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='bed_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='expected_bed_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
