# Generated by Django 4.2.7 on 2026-07-29 10:31

import clinic_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=clinic_backend.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=clinic_backend.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medications',
            field=clinic_backend.fields.EncryptedTextField(),
        ),
    ]
