# Generated by Django 4.2.7 on 2026-02-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('appointments', '0003_appointment_case_type'),
        ('patients', '0002_patient_uhid'),
        ('records', '0002_prescription_bed_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.TextField(help_text='Primary diagnosis for this visit')),
                ('symptoms', models.TextField(blank=True, help_text='Patient symptoms described', null=True)),
                ('prescription_text', models.TextField(blank=True, help_text='Medications and dosage prescribed', null=True)),
                ('notes', models.TextField(blank=True, help_text="Doctor's additional notes", null=True)),
                ('bed_required', models.BooleanField(default=False)),
                ('ward_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_bed_days', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_records', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='patients.patient')),
            ],
            options={
                'db_table': 'visit_records',
                'ordering': ['-visit_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', '-visit_date'], name='visit_recor_patient_f9fbb9_idx'), models.Index(fields=['doctor', '-visit_date'], name='visit_recor_doctor__ef8dcb_idx')],
            },
        ),
    ]
