# Generated by Django 4.2.7 on 2026-02-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_visitrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitRecord',
        ),
    ]
