# Generated by Django 4.2.7 on 2026-02-09 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_status'),
        ('records', '0005_medicalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_history', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
