# Generated by Django 4.2.7 on 2026-02-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_medicalhistory_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='prescription',
        ),
    ]
