# Generated by Django 4.2.7 on 2026-02-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_remove_medicalhistory_appointment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
